CREATE DATABASE IF NOT EXISTS mailings DEFAULT CHARACTER SET utf8;
USE mailings;

##########################PAGES################################
DROP TABLE IF EXISTS mailings;
CREATE TABLE mailings (
  email VARCHAR(255) NULL DEFAULT NULL,
  nome VARCHAR(500) NULL DEFAULT NULL,
  sexo VARCHAR(500) NULL DEFAULT NULL,
  telefone VARCHAR(500) NULL DEFAULT NULL,
  cidade VARCHAR(500) NULL DEFAULT NULL,
  estado VARCHAR(500) NULL DEFAULT NULL,
  empresa VARCHAR(500) NULL DEFAULT NULL,
  cargo VARCHAR(500) NULL DEFAULT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (email)
)  ENGINE=INNODB;
